In [1]:
# 二、简单使用

In [2]:
import tensorflow as tf

In [3]:
# 1.常数生成函数
tf.zeros([2,3], tf.int32)    # 全0
tf.ones([2,3])               # 全1
tf.fill([2,3], 7)            # 全是指定数值
tf.constant([2,3])           # 指定数组的常量

<tf.Tensor 'Const:0' shape=(2,) dtype=int32>

In [4]:
# 2.随机数生成函数
tf.random_normal([2,3], mean=0, stddev=0) # 正态分布
tf.truncated_normal([2,3])                # 正态分布，如果随机的值偏差超过2个标准差，将会重新随机
tf.random_uniform([2,3])                  # 均匀分布
tf.random_gamma([2,3], alpha=2)           # Gamma分布

<tf.Tensor 'random_gamma/Maximum:0' shape=(2, 3) dtype=float32>

In [5]:
# 使用：创建神经网络参数的变量
W = tf.Variable(initial_value=tf.random_normal([2,3], mean=0, stddev=2))    # 创建变均值为0，标准差为2的随机数矩阵

sess = tf.Session()
sess.run(W.initializer)            # 对W变量进行初始化
sess.run(W.initialized_value())    # 输出值
sess.run(W.initial_value)          # 返回tf.Variable的initial_value参数设置的值

array([[-1.360615 ,  0.3528607, -1.2578796],
       [-3.2621815, -0.7785846, -1.2923843]], dtype=float32)

In [6]:
# 3.计算
W = tf.Variable(tf.random_normal([2,3], mean=0, stddev=2))
x = tf.constant([[0.1, 0.2]])
sess = tf.Session()

y = tf.matmul(x, W)        # 矩阵叉乘，只是定义了计算图中的计算，并不是真正地运行
sess.run(W.initializer)    # 注意!变量定义时，只是给定了初始化的方法，但这个方法并未真正运行，需要通过initializer赋值

print(sess.run(y))
# sess.close()

# 附:(由于变量直接可能存在依存关系，可以通过以下方式，一次初始化所有变量)
init_op = tf.global_variables_initializer()
sess.run(init_op)

[[-0.40193573  0.02308324  0.10582612]]


In [7]:
# 4.数据占位对象 - placeholder
# TensorFlow提供了placeholder机制用于提供输入数据的位置，避免增加常量，而生成过多的节点
# 类型需要指定，但数据、维度都可以在程序运行时指定
W = tf.Variable(tf.random_normal([2,3], mean=0, stddev=2))
x = tf.placeholder(tf.float32, shape=(1,2), name='input')    # 如果维度是确定的，给出维度可以降低出错的概率
sess = tf.Session()

y = tf.matmul(x, W)        # 矩阵叉乘，只是定义了计算图中的计算，并不是真正地运行
init_op = tf.global_variables_initializer()
sess.run(init_op)

# print(sess.run(y))       # error, x is unknow
print(sess.run(y, feed_dict={x:[[0.1, 0.2]]}))
# sess.close()

[[-0.4488031   0.4264183  -0.16979326]]


In [9]:
# 附:输出log
# 使用tensorboard命令显示图示
# 命令:tensorboard --logdir=<日志的目录路径>
writer = tf.summary.FileWriter('/notebooks/data/logs', tf.get_default_graph())    # jupyter notebook的'/'目录在上一级中，通过终端可以找到
writer.close()